$LOAD_PATH << File.join(File.dirname(__FILE__), '../lib')
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'rspec'
require 'fakeweb'
require 'mojo_scraper'

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

MOJO_PAGE_SAMPLES = {
 "http://www.boxofficemojo.com/movies/?id=starwars4.htm&adjust_yr=#{Mojo::ADJUST_YEAR}" => 'starwars4.html',
 "http://www.boxofficemojo.com/movies/alphabetical.htm?letter=G&page=2&p=.htm" => 'alpha_listing_page_g.html',
 "http://www.boxofficemojo.com/alltime/domestic.htm?page=1&p=.htm" => 'domestic_listing_page_1.html',
 "http://www.boxofficemojo.com/alltime/domestic.htm?page=2&p=.htm" => 'domestic_listing_page_2.html',
 "http://www.boxofficemojo.com/alltime/domestic.htm?page=3&p=.htm" => 'domestic_listing_page_3.html'

}

# url = "http://www.boxofficemojo.com/movies/?id=starwars4.htm"
# file = File.absolute_path(File.dirname(__FILE__) + '/fixtures/starwars4.html')
# FakeWeb.register_uri(:get, url, :body => File.read(file), 
#   :content_type => "text/html")

unless ENV['LIVE_TEST']
  FakeWeb.allow_net_connect = false
  MOJO_PAGE_SAMPLES.each do |url, file_name|
    file = File.absolute_path(File.dirname(__FILE__) + "/fixtures/#{file_name}")

    # FakeWeb.register_uri(:get, url, :body => File.read(file), 
    #   :content_type => "text/html")
    #   
    
    FakeWeb.register_uri(:get, url, :response => File.read(file) )
  end
end